import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const carnation = localFont({
  src: "./Carnation.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${carnation.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {children}

        {/* 🔥 IMPORTANT: Analytics must be inside body */}
        <Analytics />

      </body>
    </html>
  );
}